name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - requests=2.24.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/sidahmed-faisal/MLflow-Pipline-for-Short-term-Rental-Prices-Prediction.git#egg=wandb-utils&subdirectory=components
